# Generated by Django 5.0.7 on 2025-05-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_organizer_validated', models.BooleanField(default=False)),
                ('validation_data', models.JSONField(blank=True, null=True)),
                ('role', models.CharField(choices=[('organisateur', 'Organisateur'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizerValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPI', models.CharField(max_length=14)),
                ('IFU', models.CharField(max_length=14)),
                ('company_name', models.CharField(max_length=255)),
                ('email_orga', models.EmailField(max_length=254, unique=True)),
                ('tel_orga', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
