# Generated by Django 5.0.7 on 2025-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizervalidation',
            name='tel_orga',
            field=models.CharField(max_length=15),
        ),
    ]
