# Generated by Django 5.0.7 on 2025-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_event', '0002_alter_organizervalidation_tel_orga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
